public with sharing class StudentJSONParser {
    public String batch_type;   //Community
    public String community_college_name;   //Ghatkopar
    public String student_firstname;    //Aafrin Amjad
    public String student_lastname; //Shaikh
    public String uid;  //2293
    public String gender;   //F
    public String expected_salary_after_antarang_career_connect;
    public String batch_code;   //GhtM20
    public String trainer_name; //Reema
    public String trainer_status;//
    public String student_contact_1;    //9820295670
    public String student_contact_2;    //
    public String student_contact_3;    //
    public String dob;  //13-Mar-2002
    public String interest_mapping_code_1;  //Artistic
    public String interest_mapping_code_2;  //
    public String aptitude_highest; //Mechanical
    public String aptitude_second_highest;  //
    public String personality_1;    //Talkative
    public String personality_2;    //Extrovert
    public String personality_3;    //
    public String personality_4;    //
    public String reality_1_self;   //
    public String reality_2_self;   //
    public String reality_3_self;   //
    public String reality_4_self;   //
    public String reality_5_family; //
    public String reality_6_family; //
    public String reality_7_family; //
    public String reality_8_family; //
    public String plan_a;   //
    public String plan_b;   //
    public String current_education;    //
    public String student_address;  //Dharamveer Sambhaji Path,opp Hotel Azad Nagar , Chirag nagar Ghatkopar west Mumbai 400086
    public String location_name;    //
    public String student_pincode;  //
    public String household_income; //0
    public String mother_education; //
    public String father_education; //
    public String mother_sector_of_employment;  //
    public String father_sector_of_employment;  //
    public String sibling1_sector_of_employment;    //
    public String sibling1_education;   //
    public String responce; // [{"responce":"An error occurred"}], [{"responce":"Invalid username or api key"}]
    public String student_email; // student email address
    public String additional_courses; // student additional course> Completed/on-going courses 
    public String working_not_through_af; // student Working right now  
    public String sector_of_employment_not_through_af; // Sector of employment 
    public String current_salary_not_through_af; // Current Salary CTC
    public String donor_name; // donor name
    public String student_Status; // Status
    public String batch_start_date;
    public String batch_end_date;
    
    //new fields added on 6th Aug'19
    public String interest_mapping_code_3;
    public String caste_certificate_present;
    public String marital_status;
    public String mother_position;
    public String father_position;
    public String monthly_family_income;
    public String no_of_siblings;
    public String currently_in_training;
    public String education_status;
    public String education_level;
    public String spoken_english_fluency;
    public String digital_literacy;
    public String completed_on_going_courses;
    
    
}